options:
  environment:
    php:
      version: 8.4
      xdebug: true
    node:
      version: 25
    server:
      enabled: true
    database:
      enabled: true
      driver: mysql
      rootPassword: docker
    mailcatcher:
      enabled: true
    rabbitmq:
      enabled: true
      managementPort: 15672
    redis:
      enabled: true